# Generated by Django 6.0.6 on 2026-06-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_studied', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lingo_deck',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('part_of_speech', models.CharField(blank=True, max_length=100)),
                ('translation', models.CharField(blank=True, max_length=500)),
                ('definition', models.TextField(blank=True)),
                ('ipa', models.CharField(blank=True, max_length=255)),
                ('example', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('learned', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'lingo_word',
            },
        ),
    ]
